fail_fast: true
repos:
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
  -
    repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.10.2
    hooks:
      - id: require-ascii

  -
    repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.13.0
    hooks:
      -
        id: markdownlint
        args: ["--config=.mdlrc"]

  -
    repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.7.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate_with_variables